import express from 'express';
import { auth } from '../middlewares/authMiddleware';
import * as urlController from '../controllers/urlController';
const router = express.Router();
router.post('/quick_create', urlController.quickCreate);
router.post('/create', auth, urlController.createShortUrl);
router.get('/dashboard', auth, urlController.getDashboard);
router.get('/search', auth, urlController.getUrl);
router.delete('/delete/:urlId', auth, urlController.deleteUrl);
router.get('/redirect/:shortUrl', urlController.redirectToUrl);
export = router;
