import express from 'express';
import { auth } from '../middlewares/authMiddleware';
import * as urlController from '../controllers/urlController';
const router = express.Router();
router.post('/quick_create', urlController.quickCreate);
router.post('/create', urlController.createShortUrl);
router.get('/dashboard', urlController.getDashboard);
router.get('/search', urlController.getUrl);
router.delete('/delete/:urlId', urlController.deleteUrl);
router.get('/redirect/:shortUrl', urlController.redirectToUrl);
export = router;
