export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';
export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const SHORTEN_URL_SUCCESS = 'SHORTEN_URL_SUCCESS';
export const SHORTEN_URL_FAILURE = 'SHORTEN_URL_FAILURE';